config/routes.rb
Rails.application.routes.draw do
  resource :login, :only => [:show]
  resources :title_lists

  root to: 'title_lists#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy',as: :logout
end

app/models/list_book.rb
class ListBook < ActiveRecord::Base
  belongs_to :title_lists
end

app/models/title_list.rb
class TitleList < ActiveRecord::Base
  belongs_to :users
  has_many :list_books
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tilte_lists,class_name: 'TilteList',foreign_key: :user_id

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user,:logged_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to login_path
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/title_lists_controller.rb
class TitleListsController < ApplicationController
  before_action :authenticate

  def index
    @title_list = TitleList.all
  end

  def new
      @keyword = params[:keyword]
      unless @keyword.nil?
        res = Amazon::Ecs.item_search(
          "",
          :title => @keyword,
          :sort => 'titlerank',
          :tag_sort => 'Name',
          :browse_node => '2250738051'
        )

         @asins = []
         res.items.each{|item| @asins << item.get('ASIN')}
         @items = Amazon::Ecs.item_lookup(@asins.join(','),:response_group => 'Large').items
      end
   #@title_list = current_user.created_title_lists.build
  end

  def create
    @title_list = current_user.created_title_lists.build(title_list_params)
    if @title_list.save
      redirect_to @title_list, notice: '新しく登録しました'
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/title_lists_helper.rb
module TitleListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReadingList</title>
  <meta charset="utf-8">
  <meta name="viewpoint" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'ReadingList', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'ログアウト', logout_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </header>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert_danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/logins/show.html.erb
<h1>ログインしてください</h1>

<p><%= link_to 'Twitterでログイン','/auth/twitter' %></p>

app/views/title_lists/index.html.erb
<h1>読んでる漫画リスト</h1>

<% @title_list.each do |item| %>
  <li>
    <img src="<%=item[:image_url]%>">
    <%=item[:list_name]%>
  </li>
<% end %>

<%= link_to 'リストの新規作成', new_title_list_path %>

app/views/title_lists/new.html.erb
<h1>リストの追加画面</h1>

<p>検索</p>
<%= form_tag(new_title_list_path,method: :get) do %>
  <%= text_field_tag(:keyword) %>
  <%= submit_tag("アマゾンで検索") %>
<% end %>

<% if @items && @items.size > 0 %>
<p>検索結果</p>
<% @items.each do |item| %>
  <li>
    <img src="<%= item.get("MediumImage/URL") %>">
    <%== item.get("ItemAttributes/Title") %>
  </li>
<% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index(test)</h1>
<p>Find me in app/views/welcome/index.html.erb</p>